spring:
  config:
    activate:
      on-profile: youngjin # 사용할 프로필명

  application:
    name: UserService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server-database.c1002c26ojgk.ap-northeast-2.rds.amazonaws.com:3306/springboot_db
    username: admin
    password: w3414078
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: false
