spring:
  config:
    activate:
      on-profile: youngjin # 사용할 프로필명

  application:
    name: UserService
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: "000000" #비밀번호 : 환경 변수로 분리하거나 Secrets Manager를 사용

jwt:
  secret: false
