spring:
  config:
    activate:
      on-profile: youngjin # 사용할 프로필명

  application:
    name: UserService
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: "000000" #비밀번호 : 환경 변수로 분리하거나 Secrets Manager를 사용

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          show_sql: true
logging:
  level:
    org.springframework.security: DEBUG