# 기본 application.yml
spring:
  profiles:
    active: woong # 사용할 프로필명

  # spring data jpa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        format_sql: true
        show_sql: true
        open-in-view: false

  mail:
    host: smtp.naver.com
    port: 465
    username: et0709@naver.com
    password: w6978979
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버 인증을 활성화
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true #STARTTLS(암호화 프로토콜)를 활성화(메일 전송 중 데이터 암호화를 지원)

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000 #Redis 서버와의 연결 타임아웃을 설정 (2초)

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.mail: DEBUG

# 인증 코드 만료 시간: 30 * 60 * 1000 == 30분
custom:
  auth-code-expiration-millis: "1800000"

# jwt 토큰 설정 관련
# 윤정 정의 속성 - /UserService/src/main/resources/META-INF/additional-spring-configuration-metadata.json
jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  # 일 단위로 설정
  expiration:
    access: 7
    refresh: 14
