spring:
  config:
    activate:
      on-profile: youngjin # 사용할 프로필명

  application:
    name: UserService

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: "000000" #비밀번호 : 환경 변수로 분리하거나 Secrets Manager를 사용

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000 #Redis 서버와의 연결 타임아웃을 설정 (2초)
jwt:
  secret: false

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.mail: DEBUG
